### ISSUE TITLE
Why check PATH before checking bundled jextract

### ISSUE THREAD

**Issue by Bartvhelvert** [krakowski/gradle-jextract#10]
I think it makes more sense for it to be the other way around. I would expect it to use the jextract that is in my current toolchain instead of the one in my PATH. Should the search order be switched?

**Comment by krakowski** [comment]
Hi @Bartvhelvert,

thanks for your interest in this project! In my understanding, the `jextract`  tool is no longer bundled with the JDK but released separately inside [this](https://github.com/openjdk/jextract) repository. Therefore I switched to checking PATH first, since the binary could be located outside the JDK folder now. If the `jextract` binary is located within the JDK's `bin` folder, then checking `PATH` should yield the same result as checking that folder explicitly.

Do you experience problems with this setup?

**Comment by Bartvhelvert** [comment]
Hi,

I don't experience any problems myself but I think if you would have a newer version of `jextract` in your `PATH`, then use an older JDK build that includes `jextract` it might cause compatibility issues. This is not the case when the plugin checks for the distributed `jextract` first. If you are using a JDK build that doesn't come with `jextract` it will check `PATH` anyway.

**Comment by krakowski** [comment]
I thought this through and the way you describe it sounds more reasonable, since in your scenario a user might have installed JDK 19 without a bundled jextract binary __and__ the standalone version of jextract for JDK 18 in PATH. Here, the generated bindings most likely would not work because of missing classes/methods.

I just pushed [`0.2.7`](https://github.com/krakowski/gradle-jextract/tree/0.2.7) where the search order is changed to reflect your proposal. Thank you! :slightly_smiling_face:
