### ISSUE TITLE
Adapt Gradle's toolchain mechanism for selecting JDKs

### ISSUE THREAD

**Issue by krakowski** [krakowski/gradle-jextract#2]
# What should this feature provide?

A way to specify the toolchain to be used for compiling and executing using [Gradle's standard mechanisms](https://docs.gradle.org/current/userguide/toolchains.html).

# Why is this feature needed?

The current way of specifying the toolchain through a custom Gradle property (`javaHome`) is not an elegant solution and may break in future Gradle versions. This will also reduce the cost of maintenance.

# How can this feature be implemented?

As explained in [Toolchains for plugin authors](https://docs.gradle.org/current/userguide/toolchains.html#sec:plugins), the custom task should expose a `toolchain` property, letting the user configure which toolchain to use.

**Comment by elect86** [comment]
I've done already this in my fork, would you like a PR?

**Comment by krakowski** [comment]
This would be great! Will this work using (just) the following snippet inside the build script?

```groovy
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}
```

**Comment by elect86** [comment]
Mostly yes.

However I added a new task to automatically download (and extract) the last Early Access build to `buildDir`

If the user doesn't have that jdk already, he can use this task and then simply assign its location to `org.gradle.java.installations.paths` in "gradle.properties`

What do you think?

Ps: I'm also working on the CI pipeline to build and release automatically snapshots in [my fork](https://github.com/elect86/panama-foreign). I'd suggest we both focus our effort on this because it's official and we can build multiple platforms (I also have macos x64 working). I just dealing now with a single damn test failing, which invalidate the whole flow and how to use properly the github action to release.

**Comment by krakowski** [comment]
Hi,

I was working on this today and got it working using Gradle's toolchain mechanism. Gradle will now autodetect the installed JDK or look in other locations specified inside `org.gradle.java.installations.paths`. Please have a look at the updated [jextract-demo](https://github.com/krakowski/jextract-demo) repository.

> However I added a new task to automatically download (and extract) the last Early Access build to `buildDir`
> 
> If the user doesn't have that jdk already, he can use this task (which will also set accordingly `org.gradle.java.installations.paths` in "gradle.properties`)
> 
> What do you think?

I would like to keep the `gradle-jextract` plugin simple in regard to its functionality. Ideally, it should just call the jextract tool. However, downloading additional JDKs could very well be implemented in a standalone plugin, as it could also be interesting for people who do not use jextract. Such a plugin could use your CI pipeline builds as a source.

> Ps: I'm also working on the CI pipeline to build and release automatically snapshots in [my fork](https://github.com/elect86/panama-foreign). I'd suggest we both focus our effort on this because it's official and we can build multiple platforms (I also have macos x64 working). I just dealing now with a single damn test failing, which invalidate the whole flow and how to use properly the github action to release.

Sounds cool! Once this is set up I could use it for my SDKMAN! installation script.
